version: '2' 
services:
  web:
    build: www/.
    ports:
     - "5000:80"
  mysql:
    build: db/.
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: 0.0.0.0
      MYSQL_USER: thomas
      MYSQL_PASSWORD: babar
    ports:
      - "3306:3306"
    volumes:
        - /srv/toto/db:/var/lib/mysql
